// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEmB7k7ESxiHwmW8Jhd62ANFskc7dTOAE',
    appId: '1:1008351180569:web:227056f95b99d5a2fdb788',
    messagingSenderId: '1008351180569',
    projectId: 'ltdnt-1bd36',
    authDomain: 'ltdnt-1bd36.firebaseapp.com',
    storageBucket: 'ltdnt-1bd36.firebasestorage.app',
    measurementId: 'G-HJZ1Q7NEQ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY1fpscRzRYHq1s0S6lCafT3eYJoTaEEM',
    appId: '1:1008351180569:android:2a7363f8c7bc549bfdb788',
    messagingSenderId: '1008351180569',
    projectId: 'ltdnt-1bd36',
    storageBucket: 'ltdnt-1bd36.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zswIDJKEAQyGNWc7Bh3g58y85sKE3bg',
    appId: '1:1008351180569:ios:1fabf7fcf571a32afdb788',
    messagingSenderId: '1008351180569',
    projectId: 'ltdnt-1bd36',
    storageBucket: 'ltdnt-1bd36.firebasestorage.app',
    iosBundleId: 'com.example.bai3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zswIDJKEAQyGNWc7Bh3g58y85sKE3bg',
    appId: '1:1008351180569:ios:1fabf7fcf571a32afdb788',
    messagingSenderId: '1008351180569',
    projectId: 'ltdnt-1bd36',
    storageBucket: 'ltdnt-1bd36.firebasestorage.app',
    iosBundleId: 'com.example.bai3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEmB7k7ESxiHwmW8Jhd62ANFskc7dTOAE',
    appId: '1:1008351180569:web:8e470a842deb1e83fdb788',
    messagingSenderId: '1008351180569',
    projectId: 'ltdnt-1bd36',
    authDomain: 'ltdnt-1bd36.firebaseapp.com',
    storageBucket: 'ltdnt-1bd36.firebasestorage.app',
    measurementId: 'G-V43NZYJNEH',
  );
}
