// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5-q87oAffWepzZKZEIRGQNaIqPeTU9M',
    appId: '1:62109794553:web:7c20b5f4acfd377960a228',
    messagingSenderId: '62109794553',
    projectId: 'flutter-app-tutorial-556a0',
    authDomain: 'flutter-app-tutorial-556a0.firebaseapp.com',
    storageBucket: 'flutter-app-tutorial-556a0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1GWn2ETiwtUrGgO8ohM0utZKa4YbJBmg',
    appId: '1:62109794553:android:8ee3e1f6e64ab01f60a228',
    messagingSenderId: '62109794553',
    projectId: 'flutter-app-tutorial-556a0',
    storageBucket: 'flutter-app-tutorial-556a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiZKj3FKiGc4N3cAGxnRI8PTf0K5EE6d0',
    appId: '1:62109794553:ios:3084294ef25da8f360a228',
    messagingSenderId: '62109794553',
    projectId: 'flutter-app-tutorial-556a0',
    storageBucket: 'flutter-app-tutorial-556a0.firebasestorage.app',
    iosBundleId: 'com.example.thuchanh4bai1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiZKj3FKiGc4N3cAGxnRI8PTf0K5EE6d0',
    appId: '1:62109794553:ios:3084294ef25da8f360a228',
    messagingSenderId: '62109794553',
    projectId: 'flutter-app-tutorial-556a0',
    storageBucket: 'flutter-app-tutorial-556a0.firebasestorage.app',
    iosBundleId: 'com.example.thuchanh4bai1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5-q87oAffWepzZKZEIRGQNaIqPeTU9M',
    appId: '1:62109794553:web:c0f2ec9410f1589660a228',
    messagingSenderId: '62109794553',
    projectId: 'flutter-app-tutorial-556a0',
    authDomain: 'flutter-app-tutorial-556a0.firebaseapp.com',
    storageBucket: 'flutter-app-tutorial-556a0.firebasestorage.app',
  );
}
